apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-{{ .Chart.Name }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
