apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: oracle
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
