version: '3.8'

services:

  oracle-db:
    image: gvenzl/oracle-xe
    container_name: oracle-xe 
    ports:
      - "1521:1521"
      - "8081:8080" 
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -S system/$${ORACLE_PASSWORD}@localhost/XEPDB1"]
      interval: 30s
      timeout: 10s
      retries: 10

  product-api:
    build: 
      context: ./api-java 
    container_name: java-api
    ports:
      - "8080:8080"
    depends_on:
      oracle-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

volumes:
  oracle_data:
