replicaCount: 1

image:
  repository: product-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources: {}

livenessProbe:
  path: /actuator/health
  port: 8080

readinessProbe:
  path: /actuator/health
  port: 8080
