replicaCount: 3

image:
  repository: fabiodinizdev/order-service
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8081

resources:
  limits:
    cpu: "1000m"
    memory: "1Gi"
  requests:
    cpu: "500m"
    memory: "512Mi"

livenessProbe:
  path: /health
  port: 8081

readinessProbe:
  path: /health
  port: 8081
