replicaCount: 1

image:
  repository: fabiodinizdev/order-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

livenessProbe:
  path: /health
  port: 8081

readinessProbe:
  path: /health
  port: 8081
