replicaCount: 1

image:
  repository: order-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

resources: {}

livenessProbe:
  path: /health
  port: 8081

readinessProbe:
  path: /health
  port: 8081
