on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      oracle:
        image: gvenzl/oracle-free:23-slim
        env:
          ORACLE_PASSWORD: oracle
        ports:
          - 1521:1521
        options: >-
          --health-cmd="grep 'DATABASE IS READY TO USE!' /container-entrypoint.log"
          --health-interval=10s --health-timeout=5s --health-retries=20
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Run ProductService tests
        run: |
          cd api-java
          ./mvnw test

      - name: Run OrderService tests
        run: |
          cd api-dotnet
          dotnet restore
          dotnet test --verbosity normal

  build-images:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build ProductService image
        run: docker build -t product-service:ci ./api-java

      - name: Build OrderService image
        run: docker build -t order-service:ci ./api-dotnet/OrderService

